shellEmulator: true

trustPolicy: no-downgrade
packages:
  - packages/*
  - apps/*
overrides:
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  diff@<8.0.3: '>=8.0.3'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@<3.14.2: '>=3.14.2'
  qs@<6.14.1: '>=6.14.1'
  tmp@<=0.2.3: '>=0.2.4'

catalog:
  '@antfu/eslint-config': ^7.0.1
  '@bull-board/api': ^6.16.2
  '@bull-board/express': ^6.16.2
  '@changesets/changelog-github': ^0.5.2
  '@changesets/cli': ^2.29.8
  '@changesets/get-github-info': ^0.7.0
  '@changesets/types': 6.1.0
  '@sindresorhus/slugify': ^2.2.1
  '@swc-node/register': ^1.10.10
  '@swc/core': ^1.11.21
  '@types/express': ^4.17.21
  '@types/glob': ^8.1.0
  '@types/jest': ^29.5.12
  '@types/lodash-es': ^4.17.12
  '@types/ms': ^2.1.0
  '@types/node': ^22.14.0
  '@types/pino': ^7.0.5
  '@types/uuid': ^10.0.0
  bullmq: 5.63.0
  camelcase: ^8.0.0
  cronstrue: ^2.59.0
  dotenv: ^16.4.7
  eslint: ^9.38.0
  eslint-plugin-format: ^1.0.2
  express: ^4.21.2
  glob: ^13.0.0
  ioredis: ^5.4.1
  jest: ^29.7.0
  lint-staged: ^15.5.0
  lodash-es: ^4.17.21
  ms: ^2.1.3
  pino: 9.14.0
  pino-pretty: ^13.0.0
  pretty-ms: ^9.2.0
  redis-memory-server: ^0.14.1
  simple-git-hooks: ^2.12.1
  tiny-lru: ^11.2.11
  ts-jest: ^29.4.6
  tsx: 4.21.0
  turbo: ^2.5.8
  typescript: 5.9.3
  uuid: ^11.1.0
  zod: ^4.1.12
