packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  '@bull-board/api': ^6.14.0
  '@bull-board/express': ^6.14.0
  '@types/express': ^4.17.21
  '@types/pino': ^7.0.5
  bullmq: 5.56.0
  express: ^4.19.2
  pino: 9.14.0
  pino-pretty: ^13.0.0
  tsx: 4.16.0
  typescript: 5.5.3
